### ISSUE TITLE
Tutorial 1 - Remix Warning

### ISSUE THREAD

**Issue by Haidy777** [bitfwdcommunity/Tutorials#1]
Hello,
I just followed your tutorial on the ERC-20 Token creation, it's really easy to follow and greatly explained.

While messing around with remix there are some warnings showing up.
Since I'm completely new in the Contract-Development-World I'm not entirely sure whats the problem, I thought I open an issue here :)

**Comment by tomterado** [comment]
Hey! 

Thanks so much for flagging that up! With regards to the Remix Error message, it's okay for their to be some errors.

As long as they are not in red, it should be okay. Yellow errors should still let you make the contract as per tutorial!

Any questions, let us know and glad you are diving down the rabbit hole with us!

**Comment by Haidy777** [comment]
I thought that they don't really matter, after all they are "only" warnings.
Maybe you should add to the medium article, so nobody gets confused.
